PROBLEM SHEET 5: This week we are going to continue learning how to use matplotlib, you will generate your own user defined functions to solve mathematical problems and we will start to explore the python package scipy, the package htat turns python into a powerful tool for scientific analysis.

* http://matplotlib.org/ is an online resource showing many examples, clicking on a graph in the gallery opens the code that produced it.

* https://www.scipy.org/ is an online resource from the developers of scipy.

### Standard Header
As we will be utilizing a number of packages with reasonably long names, we will adopt the _de facto_ standard module abbreviations in the following header.  We also ensure that our [division behavior is sensible](http://www.python.org/dev/peps/pep-0238/) by importing from `__future__`:  _i.e._, promotion to `double` will occur from `int` or `long` data types involving division:  `1/2 == 0.5`.  Although this is the default in Python 3, it is a trivial way to help this notebook work in Python 2 if that's what you are using.

In [1]:
#%matplotlib inline 
# this line is required for the plots to appear in the Jupyter cells, rather than launching the matplotlib GUI
%matplotlib widget 
#this allows interactive view but you need to be in classic rather than CoCalc Jupyter notebook for this to work

import matplotlib

import numpy as np

import matplotlib.pyplot as plt


# notice two underscores _ either side of future

## PS5 Ex1: (Marks 6/10)

Within PH2130 Mathematical Methods (see Chapter 4 of the notes) you are working with the concept of a *fourier series*, the expansion of an arbitrary periodic function $f(x)$ as a linear combination of sines and cosines, or in an exponential form. In sine and cosine form this takes the expression: $$f(x)=\frac{a_{0}}{2} + \sum_{n=1}^{\infty} [a_{n}\cos(\frac{n\pi x}{L})+b_{n}\sin(\frac{n\pi x}{L})]$$

The constants $a_{n}$ and $b_{n}$ are called *Fourier coefficients*. Notice that a coefficient $b_{0}$ is not needed as it would multiply $\sin(0) = 0$. The $a_{0}$ term contains the factor of 2 for conventional reasons as this will allow us to write down formulae for $a_{0}$ and $a_{n}$ that have a similar form.

    
**a)** Write a *user defined function* to sum the values up to the $n^{th}$ term of a fourier series to approximate a square wave of the form: $$ f(x)=\left\{
  \begin{array}{l l}
    -1 & \quad \pi\leq x \leq 2\pi\\
    1 & \quad 0 \leq x < \pi\\
  \end{array} \right.  $$


**b)** Modify your program to include a *function* to sum the values up to the $n^{th}$ term of a fourier series to approximate a saw-tooth wave of the form:

$$ f(x)= x,\qquad 0\leq x \leq \pi $$ 

**c)** Plot both functions for the sum of n up to 9, 99 and 999 as two subplots on the same figure, see example figure 1. *NOTE: to observe the Gibbs Phenomena you must have enough resolution in $x$.*

**d)** Animate a plot of the square wave so that it shows the evolution of the fourier series as more elements are added up to n=20.

<left> <img src="fourierseries.png" style="max-width:90%">
    **Figure 1:** Fourier series for a squarewave and a sawtooth 


In [7]:
#PS5 Ex1:
import numpy as np
import scipy.integrate as integrate
from matplotlib.animation import FuncAnimation

fig1 = plt.figure()
axe1 = fig1.add_subplot()
fig2 = plt.figure()
axe2 = fig2.add_subplot()

x = np.arange(0, np.pi*2, 0.01)

def square(i, n):
    """Generates a square wave for i numbers of iterations using fourier"""
    nodds = np.arange(1, n, 2)
    sum_terms = []
    for n in nodds:
        sum_term = (1/(n))*(np.sin((n*np.pi*i)/np.pi))
        sum_terms.append(sum_term)
    return (4/np.pi)*sum(sum_terms)

def plt_square(n):
    """Plots a square wave for given n fourier"""
    y = []
    for i in x:
        y.append(square(i, n))
    return y

def linear(i, n):
    """Generates a linear graph for i numbers of iterations using fourier"""
    ns = np.arange(1, n)
    sum_terms = []
    for n in ns:
        sum_term = (( np.pi*-2*(-1)**n )/( np.pi*n )) * (np.sin(( n*np.pi*i )/( np.pi )))
        sum_terms.append(sum_term)
    return sum(sum_terms)


def plt_linear(n):
    """Plots a linear graph for given n fourier"""
    y = []
    for i in x:
        y.append(linear(i, n))
    return y


# Set the x-axis ticks
axe1.set_xticks([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
axe1.set_xticklabels([r'$0$',r'$\pi/2$','$\pi$',r'$3\pi/2$',r'$2\pi$'])
# Set the y-axis ticks
axe1.set_yticks([-1,0,1])
axe1.set_yticklabels([r'-1',r'0',r'1'])
axe1.plot(x, plt_square(9), 'b', label="9")
axe1.plot(x, plt_square(99), 'g', label="99")
axe1.plot(x, plt_square(999), 'r', label="999")

# Set the x-axis ticks
axe2.set_xticks([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
axe2.set_xticklabels([r'$0$',r'$\pi/2$','$\pi$',r'$3\pi/2$',r'$2\pi$'])
# Set the y-axis ticks
axe2.set_yticks([0,np.pi/2,np.pi])
axe2.set_yticklabels([r'0',r'$\pi/2$',r'$\pi$'])
axe2.plot(x, plt_linear(9), 'b', label="9")
axe2.plot(x, plt_linear(99), 'g', label="99")
axe2.plot(x, plt_linear(999), 'r', label="999")


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

fig, ax = plt.subplots()
xdata, ydata = [], []
ln, = plt.plot([], [], 'r')

x = np.arange(0, np.pi*2, 0.01)

def square(i, n):
    nodds = np.arange(1, n, 2)
    sum_terms = []
    for n in nodds:
        sum_term = (1/(n))*(np.sin((n*np.pi*i)/np.pi))
        sum_terms.append(sum_term)
    return (4/np.pi)*sum(sum_terms)

def plt_square(n):
    y = []
    for i in x:
        y.append(square(i, n))
    return y

def init():
    # Set the x-axis ticks
    ax.set(ylim=(-2,2))
    ax.set_xticks([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
    ax.set_xticklabels([r'$0$',r'$\pi/2$','$\pi$',r'$3\pi/2$',r'$2\pi$'])
    # Set the y-axis ticks
    ax.set_yticks([-2,-1,0,1,2])
    ax.set_yticklabels(['-2','-1','0','1','2'])
    return ln,

def update(frame):
    ax.plot(x, plt_square(frame))
    return ln,


ani = FuncAnimation(fig, update, frames=np.arange(1, 20),
                    init_func=init, blit=False, repeat_delay=30000)
plt.show()

## PS5 Ex2: (Marks 4/10)

The code curvefit.py demonstrates the *scipy* function *curve\_fit()*, in this example data is generated with the functional form: $y=a\exp(-b*x) + c $ with the addition of a noise term. A curve fitting routine based on a non-linear least squares fit using a *Levenburg-Marquardt algorithm* returns the fitting parameters *popt*. *pcov* returns a 2D array which is the estimated covariance of *popt*. The diagonals provide the variance of the parameter estimate.

The syntax for *curve\_fit* and other commonly used optimisation algorithms can be found here:

http://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html

**a)** Run the example *curvefit.py* shown below, record the fit values obtained.

**b)** Modify the program *curvefit.py* such that for each point it calculates a term $yerr = \sqrt{(abs(yn-y))}$ add this to the plot as a set of error bars, use the *yerr* array as an argument for sigma to weight the least squares fit.

**[curve\_fit(f, xdata, ydata, p0=None, sigma=None, **kw)]}**

Compare the result of the fit with that of part a.


**c)** The data in file fitting_ProblemSheet5data.dat, is of the functional form $y=a\sin(bx)$, write a program to find the parameters $a$ and $b$. Plot the data, along with your best fit result.

In [2]:
#PS5Ex2:
# curvefit.py Problem Sheet 5 example
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

yerr = []

def func(x, a, b, c):
    return np.pi -a*np.exp(-b*x) + c # function to generate data for curve fit
# The first part of this program generates a set of data that follows a particular functional form that allows us to test the curvefit routine    
x = np.linspace(0,4,50)
y = func(x, 3.0, 1.3, 5)
yn = y + 0.2*np.random.normal(size=len(x)) # adding some noise to the data points

# Now that we have our data we can attempt to fit to the curve 
popt, pcov = curve_fit(func, x, yn) # performing curve fit, and returning parameters
print ('Parameters : ', popt)
print ('Covariance : ', pcov)
# graphical output of results
fig=plt.figure()
plt.scatter(x,y, label='data')
plt.scatter(x,yn, color='r', label='data + noise')
plt.errorbar(x, func(x,popt[0],popt[1],popt[2]), yerr=np.sqrt(abs(yn - y)), color='green', label='best fit')
plt.legend()
plt.show()


##Parameters :  [3.08269765 1.43872177 4.97656905]
##Covariance :  [[ 0.01668606  0.00652624  0.00067302]
## [ 0.00652624  0.01553175 -0.00437083]
## [ 0.00067302 -0.00437083  0.00256214]]



Parameters :  [3.15516336 1.15198224 5.07396649]
Covariance :  [[ 0.01750883  0.00438678  0.00145017]
 [ 0.00438678  0.01269816 -0.00602473]
 [ 0.00145017 -0.00602473  0.00472397]]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [3]:
from scipy.optimize import curve_fit

data = np.genfromtxt("fitting_ProblemSheet5data.dat")

def func(x, a, b):
    return a*np.sin(b*x)

fig, ax = plt.subplots()

popt, pcov = curve_fit(func, data.transpose()[0], data.transpose()[1])

ax.scatter(data.transpose()[0], data.transpose()[1], color="r", marker="x", label='data')
print(f'a = {popt[0]}, b = {popt[1]}')
x = np.linspace(0,2,50)
y = np.vectorize(lambda x : func(x, popt[0], popt[1]))
ax.plot(x, y(x), color='k', label='best fit')
ax.legend()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

a = 2.9858134914121535, b = 3.129224757290076


In [ ]:
#ignore this, it's something that helps styling the notebook.
from IPython.core.display import HTML
def css_styling():
    styles = open("custom.css", "r").read()
    return HTML(styles)
css_styling()